### PR TITLE
Allow discovery of logistics properties in editor

### PR DESCRIPTION
**Pull request by henrybauer**
uks1
uks2
uks3
uks4
uks5

### CODE REVIEW

**Comment by henrybauer** [comment]
See also https://github.com/BobPalmer/Kolonization/pull/16

Names and descriptions may need some editing to be 100% accurate; I just took my best guess.

**Comment by bennord** [comment]
Hey Henry, I just saw that we made overlapping changes. #45 
Great minds think alike, heh :)

I'm leaving my pull-request up, since my changes are a little different (added some GUI text in editor and in flight for RMB menus, and have some data visible in the info text, such as the various Range values).  

Anyways, looks good and sorry we overlapped!

**Comment by henrybauer** [comment]
@bennord yeah looks like we submitted the same day.

You might consider a complementary change for the "Kolonization" project (for Orbital Logistics and Planetary Logistics).  See https://github.com/BobPalmer/Kolonization/pull/16/files

I don't see KSPModule[] anywhere in your change - is it not required to get the green text (like "Power Distributor" and "Power Coupler")?  Where is that text coming from?

**Comment by bennord** [comment]
@henrybauer I didn't specify them anywhere, but they were still there. 

My guess is PartModule generates the default guiName from the classname by breaking it apart at the start of each capital letter, and removing "Module" from the start.  Hence why all of them looked good except for the obnoxiously long USI_ModuleResourceWarehouse, which defaulted to "USI_ Module Resource Warehouse".

I went ahead and explicitly set them, using your suggestion, in my changlist as well.

**Comment by BobPalmer** [comment]
Had to revert this - saw it was on MASTER.  Can you please re-do on DEVELOP?  It already has @bennord 's changes in place

**Pull request merged**
